steps:

- id: "Pull app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/personal-website-269509/mail-send-portfolio:latest']

- id: "Build app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/personal-website-269509/mail-send-portfolio:latest', '.']

- id: "Push app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/personal-website-269509/mail-send-portfolio:latest']

- id: "Deploy new app image"
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'mail-send', '--image=gcr.io/personal-website-269509/mail-send-portfolio:latest', '--region=europe-west1', '--allow-unauthenticated', '--concurrency=50', '--platform=managed', '--timeout=30s', '--max-instances=6', '--memory=128Mi']
