steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://source.developers.google.com/p/portfolio-perso-web/r/Prod-Portfolio']

- name: 'debian'
  entrypoint: 'bash'
  args: ['-c', 'pwd']

- name: 'debian'
  entrypoint: 'bash'
  args: ['-c', 'ls -a']