steps:

- id: "Build app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mail-send-portfolio:latest', '.']

- id: "Push app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mail-send-portfolio:latest']

- id: "Deploy new app image"
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'mail-send', '--image=gcr.io/$PROJECT_ID/mail-send-portfolio:latest', '--region=europe-west1', '--allow-unauthenticated', '--concurrency=40', '--platform=managed', '--timeout=20s', '--max-instances=25', '--min-instances=0', '--memory=128Mi', '--cpu=1']

timeout: 90s
