steps:

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rm', '-a', 'gs://webapp-portfolio/SendMail/*']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './index.js', 'gs://webapp-portfolio/SendMail/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './package.json', 'gs://webapp-portfolio/SendMail/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './package-lock.json', 'gs://webapp-portfolio/SendMail/']