steps:

- id: "Pull app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/portfolio-perso-237410/mail-send:latest']

- id: "Build app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/portfolio-perso-237410/mail-send:latest', '.']

- id: "Push app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/portfolio-perso-237410/mail-send:latest']

- id: "Deploy new app image"
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'mail-send', '--image=gcr.io/portfolio-perso-237410/mail-send:latest', '--region=us-central1', '--allow-unauthenticated', '--concurrency=20', '--platform=managed', '--timeout=30s']
