steps:
  
- id: "Build app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['-t', 'gcr.io/portfolio-perso-07/mail-send:latest', '.']

- id: "Push app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/portfolio-perso-07/mail-send:latest']