steps:

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rm', 'gs://webapp-portfolio/SendMail/**']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './index.js', 'gs://webapp-portfolio/SendMail/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './package.json', 'gs://webapp-portfolio/SendMail/']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './package-lock.json', 'gs://webapp-portfolio/SendMail/']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', '--config', 'https://source.developers.google.com/p/portfolio-perso-web/r/Config-Portfolio', '--no-source']