steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://source.developers.google.com/p/portfolio-perso-web/r/Prod-Portfolio']

- name: 'debian'
  entrypoint: 'bash'
  args: ['-c', 'mv index.js /Prod-Portfolio/MailSend' 'mv package.json /Prod-Portfolio/MailSend' 'mv package-lock.json /Prod-Portfolio/MailSend']